List<Map<String, String>> ratingList = [
  {
    "titleNumber": "1",
    "imageName": "assets/images/team_logo.png",
    "teamNames": "Anvar",
    "typeNumber": "56",
    "ptsNumber": "150",
  },
  {
    "titleNumber": "2",
    "imageName": "assets/images/team_logo.png",
    "teamNames": "Botir",
    "typeNumber": "42",
    "ptsNumber": "110",
  },
  {
    "titleNumber": "3",
    "imageName": "assets/images/team_logo.png",
    "teamNames": "Abbos",
    "typeNumber": "35",
    "ptsNumber": "100",
  },
  {
    "titleNumber": "4",
    "imageName": "assets/images/team_logo.png",
    "teamNames": "Farhod",
    "typeNumber": "33",
    "ptsNumber": "95",
  },
  {
    "titleNumber": "5",
    "imageName": "assets/images/team_logo.png",
    "teamNames": "Jamshid",
    "typeNumber": "32",
    "ptsNumber": "88",
  }, {
    "titleNumber": "6",
    "imageName": "assets/images/team_logo.png",
    "teamNames": "Qahramon",
    "typeNumber": "30",
    "ptsNumber": "80",
  }, {
    "titleNumber": "7",
    "imageName": "assets/images/team_logo.png",
    "teamNames": "Sobir",
    "typeNumber": "29",
    "ptsNumber": "76",
  }, {
    "titleNumber": "8",
    "imageName": "assets/images/team_logo.png",
    "teamNames": "Davron",
    "typeNumber": "27",
    "ptsNumber": "72",
  }, {
    "titleNumber": "9",
    "imageName": "assets/images/team_logo.png",
    "teamNames": "Qobil",
    "typeNumber": "25",
    "ptsNumber": "70",
  }, {
    "titleNumber": "10",
    "imageName": "assets/images/team_logo.png",
    "teamNames": "Dilshod",
    "typeNumber": "22",
    "ptsNumber": "64",
  }, {
    "titleNumber": "11",
    "imageName": "assets/images/team_logo.png",
    "teamNames": "Tursunboy",
    "typeNumber": "20",
    "ptsNumber": "60",
  }, {
    "titleNumber": "12",
    "imageName": "assets/images/team_logo.png",
    "teamNames": "Qodir",
    "typeNumber": "18",
    "ptsNumber": "56",
  }, {
    "titleNumber": "13",
    "imageName": "assets/images/team_logo.png",
    "teamNames": "Qahhor",
    "typeNumber": "15",
    "ptsNumber": "50",
  }, {
    "titleNumber": "14",
    "imageName": "assets/images/team_logo.png",
    "teamNames": "Abdulahad",
    "typeNumber": "13",
    "ptsNumber": "47",
  }, {
    "titleNumber": "15",
    "imageName": "assets/images/team_logo.png",
    "teamNames": "Javohir",
    "typeNumber": "12",
    "ptsNumber": "45",
  }, {
    "titleNumber": "15",
    "imageName": "assets/images/team_logo.png",
    "teamNames": "Tursunxon",
    "typeNumber": "10",
    "ptsNumber": "42",
  }, {
    "titleNumber": "16",
    "imageName": "assets/images/team_logo.png",
    "teamNames": "Rahmatillo",
    "typeNumber": "8",
    "ptsNumber": "30",
  },
];
