List<Map<String, String>> ratingList = [
  {
    "titleNumber": "1",
    "imageName": "assets/images/team_logo.png",
    "teamNames": "Anvar",
    "typeNumber": "31",
    "ptsNumber": "70",
  },
  {
    "titleNumber": "1",
    "imageName": "assets/images/team_logo.png",
    "teamNames": "Anvar",
    "typeNumber": "31",
    "ptsNumber": "70",
  },
  {
    "titleNumber": "1",
    "imageName": "assets/images/team_logo.png",
    "teamNames": "Anvar",
    "typeNumber": "31",
    "ptsNumber": "70",
  },
  {
    "titleNumber": "1",
    "imageName": "assets/images/team_logo.png",
    "teamNames": "Anvar",
    "typeNumber": "31",
    "ptsNumber": "70",
  },
  {
    "titleNumber": "1",
    "imageName": "assets/images/team_logo.png",
    "teamNames": "Anvar",
    "typeNumber": "31",
    "ptsNumber": "70",
  }, {
    "titleNumber": "1",
    "imageName": "assets/images/team_logo.png",
    "teamNames": "Anvar",
    "typeNumber": "31",
    "ptsNumber": "70",
  }, {
    "titleNumber": "1",
    "imageName": "assets/images/team_logo.png",
    "teamNames": "Anvar",
    "typeNumber": "31",
    "ptsNumber": "70",
  }, {
    "titleNumber": "1",
    "imageName": "assets/images/team_logo.png",
    "teamNames": "Anvar",
    "typeNumber": "31",
    "ptsNumber": "70",
  }, {
    "titleNumber": "1",
    "imageName": "assets/images/team_logo.png",
    "teamNames": "Anvar",
    "typeNumber": "31",
    "ptsNumber": "70",
  }, {
    "titleNumber": "1",
    "imageName": "assets/images/team_logo.png",
    "teamNames": "Anvar",
    "typeNumber": "31",
    "ptsNumber": "70",
  }, {
    "titleNumber": "1",
    "imageName": "assets/images/team_logo.png",
    "teamNames": "Anvar",
    "typeNumber": "31",
    "ptsNumber": "70",
  }, {
    "titleNumber": "1",
    "imageName": "assets/images/team_logo.png",
    "teamNames": "Anvar",
    "typeNumber": "31",
    "ptsNumber": "70",
  }, {
    "titleNumber": "1",
    "imageName": "assets/images/team_logo.png",
    "teamNames": "Anvar",
    "typeNumber": "31",
    "ptsNumber": "70",
  }, {
    "titleNumber": "1",
    "imageName": "assets/images/team_logo.png",
    "teamNames": "Anvar",
    "typeNumber": "31",
    "ptsNumber": "70",
  }, {
    "titleNumber": "1",
    "imageName": "assets/images/team_logo.png",
    "teamNames": "Anvar",
    "typeNumber": "31",
    "ptsNumber": "70",
  }, {
    "titleNumber": "1",
    "imageName": "assets/images/team_logo.png",
    "teamNames": "Anvar",
    "typeNumber": "31",
    "ptsNumber": "70",
  }, {
    "titleNumber": "1",
    "imageName": "assets/images/team_logo.png",
    "teamNames": "Anvar",
    "typeNumber": "31",
    "ptsNumber": "70",
  },
];
